language: ruby
rvm:
  - 2.6.2

script: "rubocop && rspec"
before_install:
  - gem build firebase_ruby_auth.gemspec
  - gem install firebase_ruby_auth --development

deploy:
  provider: rubygems
  api_key: "${RUBY_GEM_KEY}"
  gem: firebase-token-verify
  on:
    branch: gem-deploy
