language: ruby
rvm:
  - 2.6.2

before_install:
  - gem build firebase_ruby_auth.gemspec
  - gem install firebase-token-verify --development
script:
  - rubocop
  - rspec

deploy:
  provider: rubygems
  api_key: $RUBY_GEM_KEY
  gem: firebase-token-verify
  gemspec: firebase_ruby_auth.gemspec
  on:
    branch: gem-deploy
